# Change these first
owner: yorsh21 # Your GitHub organization or username, where this repository lives
repo: sites-status # The name of this repository

sites:
  - name: Insive
    url: https://insive.cl
  - name: iLuch
    url: https://iluch.com
  - name: Blinhost
    url: https://blinhost.cl
  - name: Gruber Site
    url: https://gruserv.com
  - name: Gruserv API
    url: https://app.gruserv.com
  - name: Gruserv Site
    url: https://segurapp.cl
  - name: Segurapp APP
    url: http://app.segurapp.cl
  - name: Seguridad en Linea
    url: https://seguridadenlinea.cl
  - name: Master Seguridad
    url: https://masterseguridad.cl
  - name: Escuela de Seguridad
    url: https://escueladeseguridad.cl
  - name: Limpex
    url: https://limpex.cl
  - name: Sportsalud
    url: https://sportsalud.cl/
  - name: Quiero Mi Masaje
    url: https://quieromimasaje.cl/
  - name: Bettersport
    url: https://bettersport.cl
  - name: Lumisolar Chile
    url: https://lumisolar.cl
  - name: Lumisolar Perú
    url: https://lumisolar.pe
  - name: Genera Industrial
    url: https://generaindustrial.cl
  - name: Aromalimeno
    url: https://aromalimeno.cl
  - name: Papelera Rio Claro
    url: https://papelerarioclaro.cl
  - name: Bioproject
    url: https://bioproject.cl
  - name: Renova Group
    url: https://renovagroup.cl
  - name: Messages API
    url: https://messages.insive.cl/ping
  - name: Patentes API
    url: https://patents.insive.cl/ping

assignees:
  - yorsh21

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sites-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Site Status Insive
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
